name: Deploy AWS Lambda

#Whenever push happens on main branch for changes in the folder lambda
on:
  push:
    branches:
      - main
    paths:
      - 'lambda/**'

jobs: 
  deploy-lambda: # Job name
    runs-on: ubuntu-latest # Specifies the runner
    steps:
      - uses: actions/checkout@v2 # Checks out repo code

      - name: Set Up Python # Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Dependencies # Install any packages
        run:
          python -m pip install -r lambda/requirements.txt -t lambda/  

      - name: Configure AWS Creds # Sets up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_ACCESS_SECRET_KEY}}
          aws-region: us-east-1

      - name: Deploy Lambda Function #Zips lambda directory and updates lambda function
        run: 
          cd lambda
          zip -r lambda.zip .
          aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip